### ISSUE TITLE
没看到你项目有VideoPlayer文件夹啊

### ISSUE THREAD

**Issue by saminlu** [limxing/Swift-IJKPlayer#2]
没看到你项目有VideoPlayer文件夹啊

**Comment by limxing** [comment]
VideoPlayer这个文件夹其实是一个分组，打开项目就能看到

**Comment by saminlu** [comment]
pod了 这个后 我在swift直接引入就ok吧？ 可是报错，'IJKMediaFramework/IJKMediaPlayback.h' file not found

**Comment by saminlu** [comment]
还有VideoPlayer文件夹的文件进来会和我的有些文件重名

**Comment by limxing** [comment]
IJKMediaFramework需要下载，重名的就改改呗，或者合并，很久没更，弃坑
